[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]

[build]
  command = "npm install"
  publish = "./"

[build.environment]
  NODE_VERSION = "18"

